# Generated by Django 5.0.7 on 2024-08-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=1000, verbose_name='خریدار')),
                ('id_id', models.IntegerField(verbose_name='id کالا')),
                ('number', models.IntegerField(verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش ها',
            },
        ),
    ]
