# Generated by Django 5.0.7 on 2024-08-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellmodel',
            name='number',
        ),
    ]
