# Generated by Django 5.0.7 on 2024-08-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0003_remove_sellmodel_id_id_sellmodel_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellmodel',
            name='id_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id کالا'),
        ),
    ]
