# Generated by Django 5.0.7 on 2024-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0004_sellmodel_id_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellmodel',
            name='id_id',
            field=models.IntegerField(default=2, verbose_name='id کالا'),
        ),
    ]
