# Generated by Django 5.0.7 on 2024-08-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0006_alter_sellmodel_id_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellmodel',
            name='id_id',
        ),
    ]
