# Generated by Django 5.0.7 on 2024-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0007_remove_sellmodel_id_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='More',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('off', models.IntegerField(blank=True, null=True, verbose_name='تخفیف (ریال)')),
            ],
        ),
    ]
