# Generated by Django 5.0.7 on 2024-08-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0008_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellmodel',
            name='buyer',
        ),
        migrations.AddField(
            model_name='more',
            name='buyer',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='خریدار'),
        ),
    ]
