# Generated by Django 5.1 on 2024-08-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0009_remove_sellmodel_buyer_more_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='more',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
