# Generated by Django 5.1 on 2024-08-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0010_more_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='date',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
