# Generated by Django 5.0.7 on 2024-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0011_alter_more_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellModelSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('model', models.CharField(blank=True, max_length=1000, null=True, verbose_name='مدل محصول')),
                ('color', models.CharField(blank=True, max_length=1000, null=True, verbose_name='رنگ محصول')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت محصول')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش ها',
            },
        ),
        migrations.CreateModel(
            name='Factors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=3000, null=True)),
                ('buyer', models.CharField(blank=True, max_length=1000, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('off', models.IntegerField(blank=True, null=True)),
                ('products', models.ManyToManyField(blank=True, null=True, to='Factor.sellmodelsave')),
            ],
        ),
    ]
