# Generated by Django 5.0.7 on 2024-09-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0012_sellmodelsave_factors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factors',
            old_name='products',
            new_name='productsadded',
        ),
    ]
