# Generated by Django 5.0.7 on 2024-09-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0013_rename_products_factors_productsadded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factors',
            options={'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتور ها'},
        ),
        migrations.AlterModelOptions(
            name='more',
            options={'verbose_name': 'جزییات', 'verbose_name_plural': 'جزییات ها'},
        ),
        migrations.AlterModelOptions(
            name='sellmodelsave',
            options={'verbose_name': 'ذخیره', 'verbose_name_plural': 'ذخیره ها'},
        ),
        migrations.AlterField(
            model_name='factors',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
