# Generated by Django 5.0.7 on 2025-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0014_alter_factors_options_alter_more_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='date',
            field=models.CharField(blank=True, default='1404/2/3 15:27:1', max_length=3000, null=True),
        ),
    ]
