# Generated by Django 5.0.7 on 2025-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0015_alter_more_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellmodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sellmodelsave',
            name='color',
        ),
        migrations.AlterField(
            model_name='more',
            name='date',
            field=models.CharField(blank=True, default='1404/2/3 15:47:42', max_length=3000, null=True),
        ),
    ]
