# Generated by Django 5.0.7 on 2025-04-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0016_remove_sellmodel_color_remove_sellmodelsave_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='date',
            field=models.CharField(blank=True, default='1404/2/3 15:49:15', max_length=3000, null=True),
        ),
    ]
