# Generated by Django 5.0.7 on 2025-04-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0017_alter_more_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='date',
            field=models.CharField(blank=True, default='1404/2/3 15:54:20', max_length=3000, null=True),
        ),
    ]
