# Generated by Django 5.0.7 on 2024-08-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signin', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserOfSite',
        ),
    ]
