# Generated by Django 5.0.7 on 2024-08-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='title',
            new_name='subject',
        ),
    ]
