# Generated by Django 5.1 on 2024-08-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_rename_title_contactus_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=11, verbose_name='شماره تلفن'),
        ),
    ]
