# Generated by Django 5.1 on 2024-08-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_alter_contactus_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
    ]
