# Generated by Django 5.0.7 on 2024-08-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0005_alter_contactus_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='response',
        ),
    ]
