# Generated by Django 5.0.7 on 2024-09-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10000000)),
                ('price', models.CharField(max_length=300, verbose_name='قیمت')),
                ('model', models.CharField(max_length=300, verbose_name='مدل')),
                ('color', models.CharField(max_length=300, verbose_name='رنگ')),
                ('kind', models.CharField(max_length=3000)),
                ('details', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
    ]
