# Generated by Django 5.1 on 2024-08-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('model', models.CharField(max_length=300, verbose_name='مدل')),
                ('color', models.CharField(max_length=300, verbose_name='رنگ')),
                ('number_of_availables', models.IntegerField(verbose_name='تعداد محصول موجود')),
            ],
            options={
                'verbose_name': 'مبل',
                'verbose_name_plural': 'مبلمان',
            },
        ),
    ]
