# Generated by Django 5.1 on 2024-08-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('model', models.CharField(max_length=300, verbose_name='مدل')),
                ('color', models.CharField(max_length=300, verbose_name='رنگ')),
                ('number_of_availables', models.IntegerField(verbose_name='تعداد محصول موجود')),
                ('available', models.BooleanField(verbose_name='موجود بودن')),
            ],
            options={
                'verbose_name': 'اداری',
                'verbose_name_plural': 'اداری ها',
            },
        ),
        migrations.CreateModel(
            name='Roy_sleeps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('model', models.CharField(max_length=300, verbose_name='مدل')),
                ('color', models.CharField(max_length=300, verbose_name='رنگ')),
                ('number_of_availables', models.IntegerField(verbose_name='تعداد محصول موجود')),
                ('available', models.BooleanField(verbose_name='موجود بودن')),
            ],
            options={
                'verbose_name': 'سرویس خواب',
                'verbose_name_plural': 'سرویس های خواب',
            },
        ),
        migrations.CreateModel(
            name='wood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('model', models.CharField(max_length=300, verbose_name='مدل')),
                ('color', models.CharField(max_length=300, verbose_name='رنگ')),
                ('number_of_availables', models.IntegerField(verbose_name='تعداد محصول موجود')),
                ('available', models.BooleanField(verbose_name='موجود بودن')),
            ],
            options={
                'verbose_name': 'چوب',
                'verbose_name_plural': 'چوب ها',
            },
        ),
        migrations.AddField(
            model_name='sofa',
            name='available',
            field=models.BooleanField(default=False, verbose_name='موجود بودن'),
        ),
    ]
