# Generated by Django 5.1 on 2024-08-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_administrative_roy_sleeps_wood_sofa_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=300, verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('model', models.CharField(max_length=300, verbose_name='مدل')),
                ('color', models.CharField(max_length=300, verbose_name='رنگ')),
                ('number_of_availables', models.IntegerField(verbose_name='تعداد محصول موجود')),
                ('available', models.BooleanField(default=False, verbose_name='موجود بودن')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('kind', models.ManyToManyField(blank=True, to='products.kind')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.DeleteModel(
            name='administrative',
        ),
        migrations.DeleteModel(
            name='Roy_sleeps',
        ),
        migrations.DeleteModel(
            name='Sofa',
        ),
        migrations.DeleteModel(
            name='wood',
        ),
    ]
