# Generated by Django 5.1 on 2024-08-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_kind_products_delete_administrative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='kind',
            field=models.ManyToManyField(blank=True, related_name='Kind', to='products.kind', verbose_name='دسته'),
        ),
    ]
