# Generated by Django 5.1 on 2024-08-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_id_alter_products_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='عکس1'),
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='عکس2'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='عکس3'),
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='عکس4'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
