# Generated by Django 5.1 on 2024-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_image1_products_image2_products_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor', models.CharField(max_length=500, verbose_name='طلبکار')),
                ('amount_of_debt', models.IntegerField(verbose_name='مقدار بدهی (ریال)')),
                ('payment_deadline', models.DateField(verbose_name='(به میلادی)مهلت پرداخت')),
            ],
            options={
                'verbose_name': 'بدهی',
                'verbose_name_plural': 'بدهی ها',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor', models.CharField(max_length=500, verbose_name='بدهکار')),
                ('amount_of_debt', models.IntegerField(verbose_name='مقدار طلب (ریال)')),
                ('payment_deadline', models.DateField(verbose_name='(به میلادی)مهلت پرداخت')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'طلب ها',
            },
        ),
    ]
