# Generated by Django 5.1 on 2024-08-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_debts_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='available',
        ),
        migrations.RemoveField(
            model_name='products',
            name='number_of_availables',
        ),
    ]
