# Generated by Django 5.1 on 2024-08-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_products_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.IntegerField(default=1, verbose_name='کد'),
        ),
    ]
