# Generated by Django 5.1 on 2024-08-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='code',
        ),
    ]
