# Generated by Django 5.1 on 2024-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_products_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
