# Generated by Django 5.1 on 2024-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='kind',
            field=models.ManyToManyField(related_name='Kind', to='products.kind', verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
    ]
