# Generated by Django 5.1 on 2024-08-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_products_kind_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Images/', verbose_name='عکس1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Images/', verbose_name='عکس2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, upload_to='Images/', verbose_name='عکس3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.ImageField(blank=True, upload_to='Images/', verbose_name='عکس4'),
        ),
    ]
