# Generated by Django 5.1 on 2024-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_products_image1_alter_products_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=300, verbose_name='قیمت'),
        ),
    ]
