# Generated by Django 5.1 on 2024-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(max_length=300000, verbose_name='اسم محصول')),
                ('product_color', models.CharField(max_length=300000, verbose_name='رنگ محصول')),
                ('Buyer', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی خریدار')),
                ('Phone_one', models.CharField(max_length=300, verbose_name='شماره همراه اول')),
                ('Phone_two', models.CharField(max_length=300, verbose_name='شماره همراه دوم')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('Adress', models.CharField(max_length=100000, verbose_name='آدرس')),
            ],
        ),
    ]
