# Generated by Django 5.0.7 on 2024-08-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_products_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
