# Generated by Django 5.1 on 2024-08-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_color',
            field=models.CharField(blank=True, max_length=300000, null=True, verbose_name='رنگ محصول'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_model',
            field=models.CharField(blank=True, max_length=300000, null=True, verbose_name='اسم محصول'),
        ),
    ]
