# Generated by Django 5.0.7 on 2024-08-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_orders_is_read_alter_orders_product_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
    ]
