# Generated by Django 5.0.7 on 2024-08-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_orders_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Adress',
            new_name='Address',
        ),
    ]
