# Generated by Django 5.0.7 on 2024-08-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_rename_adress_orders_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'بستانکار', 'verbose_name_plural': 'بستانکار ها'},
        ),
    ]
