# Generated by Django 5.0.7 on 2024-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_userofsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000, verbose_name='نام کاربری')),
                ('review', models.TextField(verbose_name='نظر')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviews', to='products.reviews', verbose_name='نظرات'),
        ),
    ]
