# Generated by Django 5.0.7 on 2024-08-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_reviews_products_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id محصول'),
        ),
    ]
