# Generated by Django 5.0.7 on 2024-08-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_reviews_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='product_id',
            field=models.IntegerField(verbose_name='id محصول'),
        ),
    ]
