# Generated by Django 5.0.7 on 2024-08-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_reviews_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
