# Generated by Django 5.0.7 on 2024-09-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_reviews_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='reviews',
        ),
    ]
