# Generated by Django 5.0.7 on 2025-04-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_products_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='رنگ'),
        ),
    ]
